### PR TITLE
Polylines

### PR DESCRIPTION
**Pull request by krezzoid**
a lot of code refactored

added ability to display routes on AR view

### CODE REVIEW

**Comment by intere** [comment]
@krezzoid - can you please address the merge conflicts in this PR?

**Comment by krezzoid** [comment]
@intere hi
well ... this pull-request was made one year ago ;) anyway, I will take a look this next weekend, unfortunately don't have enough time to do this before

**Comment by intere** [comment]
@krezzoid - I take it you've been busy.  Any chance you might have some time to update this?  I'm (not currently) a member of this project, so I can't update your PR for you.

**Comment by krezzoid** [comment]
hi @intere unfortunately I don't have write access to be able merge this pull-request

**Comment by intere** [comment]
@krezzoid - could you fork this repo, checkout this branch, fix the merge conflicts and then submit a new PR?

**Comment by krezzoid** [comment]
@intere can you use the sources from forked repo?
https://github.com/wemap/ARKit-CoreLocation/tree/polylines

this repo contains these fixes and merge conflicts appear only in this, original, repository.

**Comment by intere** [comment]
the issue is the merge conflicts, not the source...

**Comment by intere** [comment]
I spent most of yesterday working on this PR.  I'll close this one in lieu of an updated PR: https://github.com/ProjectDent/ARKit-CoreLocation/pull/159 that has no merge conflicts.

**Comment by aaronbrethorst** [comment]
closing in favor of #159. thanks for your work on this.

**Pull request closed without merging**
