### PR TITLE
Addresses Issue #136 - ARCL lacks CI

### PR DESCRIPTION
**Pull request by intere**
### Background
In an effort to setup CI (and address [Issue #136](https://github.com/ProjectDent/ARKit-CoreLocation/issues/136)) for ARCL I've done the following
- Reached out to @ProjectDent to see about getting admin access to this repo so I can setup TravisCI
- Added a Gemfile (that adds cocoapods and fastlane)
- Added a `Fastfile` and a `test` lane that:
   - does a `pod intall`, then
   - compiles and runs the tests
- Updated `.travis.yml` to run the tests
- Edited the build phase to `NOT` run swiftlint in the CI environment, because it apparently ignores our `.swiftlint.yml` file.  ¯\\\_(ツ)\_/¯ 

`Check out` [Travis CI](https://travis-ci.org/ProjectDent/ARKit-CoreLocation)
Here's a badge for this PR: [Build Status](https://travis-ci.org/ProjectDent/ARKit-CoreLocation)

### TODO
- [x] Update README
- [x] Update changelog
- [x] Setup TravisCI

### Breaking Changes
N/A

### Meta
- Tied to Version Release(s): 1.2.1

### Checklist

- [x] Appropriate label has been added to this PR (i.e., Bug, Enhancement, etc.).
- [ ] Documentation has been added to all `open`, and `public` scoped methods and properties.
- [x] Changelog has been updated
- [x] Tests have have been added to all new features. (not a requirement, but helpful)
- [ ] Image/GIFs have been added for all UI related changed.

### CODE REVIEW

**Comment by ProjectDent** [comment]
I did see a message from you recently requesting access for this, but I can't find that message now. Also looked into setting up Owner access but doesn't look like a regular or straight-forward process.

Normally if there's a task which requires Owner permissions, Aaron asks me if I can do it, for example setting up a different default branch.

Are there some steps I can take to help with this setup?

**Comment by intere** [comment]
@ProjectDent - you should be able to just login (using your GH account) to https://travis-ci.org/ and then add this project to TravisCI.

There should be a button like this:
image

After doing that, can you ensure that the settings for this project look like this?
image

**Comment by ProjectDent** [comment]
Done - lmk if it's been setup correctly or anything more needs doing.

**Comment by intere** [comment]
@ProjectDent - it looks to be setup.  I just merged with `develop`, pushed up and now it's triggered TravisCI.  Thanks for the help!

**Comment by intere** [comment]
@aaronbrethorst - This is passing, I'm just going to merge it into `develop`

**Pull request merged**
