### PR TITLE
Add a tag to LocationNode base class and ability to find nodes w/specific tags in a scene

### PR DESCRIPTION
**Pull request by dhmspector**
- Added a string tag to the base LocationNode class
- Added a method the SceneLocationView to determine if a node with a specified tag exists in the scene.

This addition makes it easier to modify scene contents by adding the ability to reason about aces that may be in the scene.

### CODE REVIEW

**Comment by ProjectDent** [comment]
Thanks for the PR!

Trying to figure out if there's a cleaner way of doing this. What's your own usage of this, and what's it designed to achieve? Is there another area of iOS where you see this pattern used, or where you see it solved with a different solution?

**Comment by dhmspector** [comment]
My thought process was that it would be helpful if there was a way to reason about nodes in the scene and decide if you needed to remove them or otherwise manipulate them. This is part of a larger effort I am working (the node update protocol I mentioned on slack) that will help dynamically manage content flowing into and out of the AR session.

The way I am using this is the I have actually two objects I work with in using ARCL - the first is an "ARPlace" - this is a generic place object that includes the lat/lon needs to place a node in the scene. The other is a vObject -- a virtual content object.  ARPlaces can have zero or more virtual content objects (for example, HTML pages, movies, images, whatever) depending on the situation. The ARPlace's ID (a UUID string) is added to the tag in my forked version of the Location node. And, as the user moves around I can make a decision on how to change the node's presentation (if the node goes out of visible range the web browser turns into a floating tag, father still and it disappears completely, etc).

Being able to quickly locate the node allows me to then act on any changes I may need to make to it in the scene.   

As far as I know there is no other way to easily locate a node in the scene short of looping over all the nodes and looking at each node's coordinates. And there are many  frameworks use string tags in their base classes ([Eureka](https://eurekacommunity.github.io) -- the really nice form system for  for example) to allow users to find elements based on an application specific tag.

Hope this is helpful!

**Comment by francisjervis** [comment]
@dhmspector I was able to add tags to a node to handle taps on billboards, but could not access the data from my scene class's touchesBegan function. Trying to access the .tag property of the scene node returned from self.sceneLocationView.hitTest results in a "Value of type 'SCNNode' has no member 'tag'" error. Is there a way around this?

**Comment by dhmspector** [comment]
@francisjervis   Hmmm... I haven't seen that happen. It's also been a few weeks since I have touched my demo app (other work priorities since I did our initial ARKit demo) - let me try it and see what I get.

**Comment by aaronbrethorst** [comment]
Merged in #107 — thank you!

**Pull request closed without merging**
