### PR TITLE
Feature/location node touch

### PR DESCRIPTION
**Pull request by developerark**
Added a touch delegate to return the SCNNode that is being touched using hitTest

### CODE REVIEW

**Comment by developerark** [comment]
@ProjectDent @aaronbrethorst review

**Comment by Sibaiur** [comment]
Hi, complete noob here.
Thanks for making this, I have been able to add a UIView and the touch delegate.
I just wanted to know if it was possible to access the UIView attached to the SCNNode, and how I should do that. 
Thanks!

**Comment by developerark** [comment]
I have opened an issue in my fork. Here is the link
https://github.com/developerark/ARKit-CoreLocation/issues/2

**Comment by developerark** [comment]
Solved with PR #153. Now in master

**Pull request closed without merging**
