### PR TITLE
Fixed coordinateWithBearing

### PR DESCRIPTION
**Pull request by futuretap**
calculating metersToLongitude is wrong because it depends on latitude!

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
@futuretap do you have any suggestions on the best way to test this PR?

**Comment by futuretap** [comment]
No. You can google Haversine formula if you’re in doubt.

**Comment by futuretap** [comment]
In any case, the current approach of using a constant to convert meters to longitude is quite a joke.

**Comment by banaslee** [comment]
Any idea when this is going to get merged?

**Comment by aaronbrethorst** [comment]
Fixed with #122. Thanks for the PR.

**Pull request closed without merging**
