### PR TITLE
added a uiview in locationNode class

### PR DESCRIPTION
**Pull request by gauravkeshre**
Added the ability to render UIView inside LocationAnnotationNode

### CODE REVIEW

**Comment by gauravkeshre** [comment]
@ProjectDent Please have a look and suggest edits.

**Comment by ProjectDent** [comment]
I don't know that this is the right way to be implementing this. I believe all you need is additional features on `LocationAnnotationNode`:
1. A function which snapshots a UIView and creates an image, which could then be initialised as a `LocationAnnotationNode`.
2. A convenience initialiser which takes a UIView and uses the snapshot feature itself.
3. An `update` feature, where you can declare that the UIView has been updated (perhaps its content changed, perhaps a frame change), and thus a new snapshot should be taken.

**Comment by gauravkeshre** [comment]
> I don't know that this is the right way to be implementing this. I believe all you need is additional features on `LocationAnnotationNode`:
> 
> 1. A function which snapshots a UIView and creates an image, which could then be initialised as a `LocationAnnotationNode`.
> 2. A convenience initialiser which takes a UIView and uses the snapshot feature itself.
> 3. An `update` feature, where you can declare that the UIView has been updated (perhaps its content changed, perhaps a frame change), and thus a new snapshot should be taken.

This makes sense. I have ended up doing something similar. 
Will update the PR with your feedback.

**Comment by developerark** [comment]
I have fixed this with PR #147 
Review and merge. :)

**Comment by gauravkeshre** [comment]
sure

**Comment by developerark** [comment]
> > I don't know that this is the right way to be implementing this. I believe all you need is additional features on `LocationAnnotationNode`:
> > 
> > 1. A function which snapshots a UIView and creates an image, which could then be initialised as a `LocationAnnotationNode`.
> > 2. A convenience initialiser which takes a UIView and uses the snapshot feature itself.
> > 3. An `update` feature, where you can declare that the UIView has been updated (perhaps its content changed, perhaps a frame change), and thus a new snapshot should be taken.
> 
> This makes sense. I ended up doing something similar.
> Will update the PR with your feedback.

@ProjectDent you can set the SCNPlanes firstMaterial.diffuse.content to a UIView. Solved in the PR #147

**Comment by developerark** [comment]
@gauravkeshre @ProjectDent check PR #150. I have implemented the code to handle this and node touch notification and more.

**Comment by aaronbrethorst** [comment]
Enabled in #153

**Pull request closed without merging**
