### PR TITLE
Removes flicker

### PR DESCRIPTION
**Pull request by Pilot-Marc**
### Remove flicker on overlapping nodes

SceneKit defaults the z-order of all nodes to 0, which causes flicker for overlapping nodes.  This change assigns a random z-order value to each node, with the ability to override that random value if you want to control which node is in front / behind the other.  

### Breaking Changes
N/A

### Meta
- Tied to Version Release(s):

### Checklist

- [x] Appropriate label has been added to this PR (i.e., Bug, Enhancement, etc.).
- [x] Documentation has been added to all `open`, and `public` scoped methods and properties.
- [ ] Changelog has been updated
- [ ] Tests have have been added to all new features. (not a requirement, but helpful)
- [ ] Image/GIFs have been added for all UI related changed.

### Screenshots

### CODE REVIEW

**Comment by intere** [comment]
@Pilot-Marc - can you please update the changelog?

**Comment by intere** [comment]
I'm recreating your PR to clean it up.  I'm doing the following to clean things:
```
1. ` git checkout -b feature/removeFlicker`
2. `git fetch upstream` - make sure I'm up to date with develop in this repo
3. `git fetch pilot-marc` - make sure I've got everything from your fork
4. `git reset --hard upstream/develop` - start at whatever the current develop branch is
5. `git cherry-pick 17dc9e9` - First commit relevant to this PR "Remove flicker by assigning non-conflicting z-order values to each node"
6. `git cherry-pick 5a5abd3` - Next relevant commit: "Convert TAB -> Space"
7. `git cherry-pick d9cfe75` - Next relevant commit: "Convert TAB -> Space"
8. `git cherry-pick febbd0a` - The Comment commit: "Update ChangeLog for PR 203" 👈 This is the one that was missing
9. `git push origin feature/removeFlicker` 👈  pushed up to my fork: [@intere/ARKit-CoreLocation](https://github.com/intere/ARKit-CoreLocation/tree/feature/removeFlicker)
```

**Comment by SteveNewhouse** [comment]
This getting released soon?  Looking fwd to it.

**Comment by intere** [comment]
Yeah, we can probably cut a minor release.  There are more PRs that I haven't gotten around to yet.

**Comment by intere** [comment]
I've added an issue to do this: https://github.com/ProjectDent/ARKit-CoreLocation/issues/218

**Pull request merged**
