### PR TITLE
Scaling Schemes

### PR DESCRIPTION
**Pull request by Thomasp1**
added different methods of scaling annotation size based on distance.

### CODE REVIEW

**Comment by alexandremorgado** [comment]
Seems very interesting @Thomasp1  

Can you show some examples of using threshold, scale, buffer, etc?  What values you suggest to use for tests? threshold are related to distance, in meters? 

Thank you for sharing!

**Comment by Thomasp1** [comment]
Hey, sorry for not responding for so long,

Yes, the values are meters. Threshold defines at what distance the change in scale kicks in. e.g. in tiered where threshold is 3.0 and scale is 0.5, the nodes' will halve their scale when the their distance is beyond 3 meters from the user. In regards to linear, since we can already define a starting scale for the nodes, setting the threshold defines how gradual or quick the node's scaling changes. In linear, anything past the threshold has a scaling of 0. linearbuffer is the same, but lets you define an increase amount of distance before the scaling activates, whereas linear is immediate.

**Comment by aaronbrethorst** [comment]
Hey @jdarowski - thanks for making those changes. Can you rebase against master?

**Comment by jdarowski** [comment]
Hi @aaronbrethorst, do you mean just my commit or all in this pull request? It's been up for quite some time.

**Comment by intere** [comment]
@Thomasp1 - could you please take a look at (and test) https://github.com/ProjectDent/ARKit-CoreLocation/pull/183?  I've recreated this PR in the updated codebase.

**Comment by intere** [comment]
closing in favor of https://github.com/ProjectDent/ARKit-CoreLocation/pull/183

**Pull request closed without merging**
