### PR TITLE
add Jazzy-generated documentation

### PR DESCRIPTION
**Pull request by halmueller**
### Background

Added .jazzy.yaml configuration file. Ran Jazzy to generate HTML documentation in "docs" directory, in preparation for turning on Github pages. Also generated docset in "docs/docsets".

To view documentation locally, open docs/index.html with your favorite browser. Firefox seems to cope better with the remote images than Safari does.

### Breaking Changes
None

### Meta
- Tied to Version Release(s):

### PR Checklist
- [ ] CI runs clean?
- [ ] Appropriate label has been added to this PR (i.e., Bug, Enhancement, etc.).
- [ ] Documentation has been added to all `open`, and `public` scoped methods and properties.
- [ ] Changelog has been updated
- [ ] Tests have have been added to all new features. (not a requirement, but helpful)
- [ ] Image/GIFs have been added for all UI related changed.

### CODE REVIEW

**Comment by Pilot-Marc** [comment]
image

Tried Chrome first, saw three missing images.  Caveat: I haven't done any debugging to see what the problem is yet.

**Comment by halmueller** [comment]
Not quite ready for prime time, I think, given the image troubles and the hackery I'm doing to use the Pods folder.

**Comment by Pilot-Marc** [comment]
Just a guess here, but the image is enclosed in an HREF to link to that very image.  Remove the encompassing `<a></a>` and the three images _should_ work.

**Comment by halmueller** [comment]
Closed in favor of https://github.com/ProjectDent/ARKit-CoreLocation/commit/2f5a8bfb237b4806c2f8eddfcdf95414886627e3.

**Pull request closed without merging**
