### PR TITLE
Created version 1.1.0

### PR DESCRIPTION
**Pull request by intere**
### Background
Create a new version of the library: 1.1.0
After this PR is merged in, We'll need to tag master and then push the pod to cocoapods (I can tackle that).

### Breaking Changes
N/A

### Meta
- Tied to Version Release(s): 1.1.0

### Checklist

- [x] Appropriate label has been added to this PR (i.e., Bug, Enhancement, etc.).
- [x] Changelog has been updated

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
@intere are you planning on pushing the changes to Cocoapods or shall I do that?

**Comment by intere** [comment]
@aaronbrethorst I'm on it, thanks for asking!

**Comment by intere** [comment]
@aaronbrethorst - I take it back:
```
[!] You (intere@gmail.com) are not allowed to push new versions for this pod. The owners of this pod are aaron@brethorsting.com and andrew@projectdent.com.
```

**Comment by aaronbrethorst** [comment]
@intere weird, I thought you were added to that... hmm, ok. on it.

**Comment by aaronbrethorst** [comment]
@intere published 🎉

**Comment by intere** [comment]
thanks for the help @aaronbrethorst

I've also created a release: https://github.com/ProjectDent/ARKit-CoreLocation/releases/tag/1.1.0

**Pull request merged**
